apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-rest-jreendpoint
  labels:
    app: java-rest-jreendpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-rest-jreendpoint
  template:
    metadata:
      labels:
        app: java-rest-jreendpoint
    spec:
      containers:
      - name: java-rest-jreendpoint
        image: hatta1212/restjavaapi:jreendpoint # Replace with your image
        ports:
        - containerPort: 8080
        livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
        readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
        startupProbe:
            failureThreshold: 60
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
