apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-rest-api-liberica
  labels:
    app: java-rest-api-liberica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-rest-api-liberica
  template:
    metadata:
      labels:
        app: java-rest-api-liberica
    spec:
      containers:
      - name: java-rest-api-liberica
        image: hatta1212/restjavaapi:liberica-09 # Replace with your image
        ports:
        - containerPort: 8080
        livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
        readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
       # startupProbe:
       #     failureThreshold: 30
       #     httpGet:
       #       path: /actuator/health/startup
       #       port: 8080
       #       scheme: HTTP
       #     periodSeconds: 10
            #successThreshold: 1
            #timeoutSeconds: 5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
