apiVersion: v1
kind: Service
metadata:
  name: java-rest-api-liberica
  labels:
    app: java-rest-api-liberica
spec:
  selector:
    app: java-rest-api-liberica
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
